{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devoops-service.fullname" . }}
  labels:
    {{ include "devoops-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
