fullnameOverride: devoops-mongodb

global:
  security:
    allowInsecureImages: true

auth:
  rootUser: devoops
  rootPassword: devoops

image:
  registry: docker.io
  repository: bitnamilegacy/mongodb
  tag: 7.0.9

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

persistence:
  enabled: true
  size: 1Gi

service:
  type: ClusterIP
  ports:
    mongodb: 27017
