{
 "title": "Container & OS Metrics",
 "tags": [
  "containers",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_usage_seconds_total{name=~\"devoops-.*\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Host metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[5m]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Host Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/\"} / 1024 / 1024",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Host Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[5m])) + sum(rate(container_network_transmit_bytes_total{id=\"/\"}[5m]))",
     "legendFormat": "Host Troughput"
    }
   ]
  },
  {
   "title": "Host Filesystem Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\", device=~\"/dev.*\"}) / 1024 / 1024 / 1024"
    }
   ]
  },
  { "title": "Container metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Container CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"$container\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"$container\"} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"$container\"}[5m]) + rate(container_network_transmit_bytes_total{name=~\"$container\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Filesystem Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=~\"$container\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}