{
 "title": "Web Traffic Metrics",
 "tags": [
  "web",
  "traffic",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(http_server_requests_seconds_count{job=\"gateway-service\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Successful Requests (2xx, 3xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(http_server_requests_seconds_count{job=\"gateway-service\",status=~\"2..|3..\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Failed Requests (4xx, 5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(http_server_requests_seconds_count{job=\"gateway-service\",status=~\"4..|5..\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "stat",
   "description": "Unique visitors by IP + User-Agent in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (visitor_hash) (increase(http_visitor_request_total[$__range]) > 0))"
    }
   ]
  },
  {
   "title": "Top 404 Errors by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, round(sum by (uri) (increase(http_server_requests_seconds_count{job=\"gateway-service\",status=\"404\", uri!=\"/**\"}[$__range])))) > 0"
    }
   ]
  },
  {
   "title": "Total Traffic (24h)",
   "type": "stat",
   "description": "Total HTTP request and response bytes in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_traffic_bytes_request_total{job=\"gateway-service\"}[24h])) + sum(increase(http_traffic_bytes_response_total{job=\"gateway-service\"}[$__range]))) / 1073741824"
    }
   ]
  }
 ]
}