fullnameOverride: devoops-postgres

global:
  security:
    allowInsecureImages: true

auth:
  postgresPassword: devoops123
  username: devoops
  password: devoops123
  database: devoops

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0

primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  persistence:
    enabled: true
    size: 2Gi

service:
  type: ClusterIP
  ports:
    postgresql: 5432
